id: PA081D191
initial_creation_type: input
source_metadata:
  Title: Journal of the Royal Asiatic Society
  Editor: Bendall, Cecil
  Publisher: Trübner and Company
  Place of Publication: London
  Year: '1880'
  Megha sūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:05:17.726460'
last_modified_at: '2022-03-08T16:05:17.726468'
